---
apiVersion: v1
kind: Service

metadata:
  name: nginx-svc
  namespace: default

# Specification to include ports Selector to connect to deployment
spec:
  ports:
  - nodePort: 30442 # range 30000 - 32768
    port: 80 # port to use on localhost
    protocol: TCP
    targetPort: 80 # target our app uses 

# Define the selector and label to connect to nginx deployment
  selector:
    app: nginx # this label connects this service to deployement

  # Creating LoadBalancer type of deployement
  type: LoadBalancer